pipeline {
    agent none
    environment {
        FLASK_ENV = 'docker'
    }
    stages {
        //stage('Gen creds') {
          //agent { docker { image 'python:3.7.4' } }
            //steps {
              //sh 'pip install boto3==1.9.209'
              //sh 'python gen_creds_for_db.py'
            //}
        //}
        stage('Building') {
            agent any
            steps {
                withPythonEnv('/usr/bin/python3') {
                    sh 'python --version'
                    sh 'pip3 install boto3==1.9.209'
                    sh 'python3 gen_creds_for_db.py'
    // Uses the default system installation of Python
    // Equivalent to withPythonEnv('/usr/bin/python')
}
             dir ('Project/jenkins/') {
                  sh 'make build'
                }
                    }
        }
        stage('Destroying') {
            agent any
            steps {
           dir ('Project/jenkins/') {
                sh 'make down'
              }
            }
        }
    }
}
