pipeline {
    agent none
    environment {
        FLASK_ENV = 'docker'
    }
    stages {
        stage('Building') {
            agent any
            steps {
                withPythonEnv('/usr/bin/python3') {
                    sh 'pip3 install boto3==1.9.209'
                    sh 'pip3 install Flask==1.1.1'
                    sh 'pip3 install Flask-RESTful==0.3.7'
                    sh 'pip3 install arrow==0.14.5'
                    sh 'python3 gen_creds_for_db.py'
}
             dir ('Project/jenkins/') {
                  sh 'make build'
                }
                    }
        }
        stage('Destroying') {
            agent any
            steps {
           dir ('Project/jenkins/') {
                sh 'make down'
              }
            }
        }
    }
}
